### PR TITLE
Fix refs automatically set to nullable

### PR DESCRIPTION
**Pull request by momala454**
Fixes the issue mentioned on https://github.com/zircote/swagger-php/pull/1391#issuecomment-1383826332

### CODE REVIEW

**Comment by momala454** [comment]
can someone please look at my pull requests please ?

**Comment by DerManoMann** [comment]
Thanks @momala454 and apologies for the delay.

**Comment by momala454** [comment]
thanks @DerManoMann 
I think the tests on https://github.com/zircote/swagger-php/pull/1391 should pass now

**Comment by DerManoMann** [comment]
> thanks @DerManoMann I think the tests on #1391 should pass now

I guess you'll need to rebase your branch then?

**Pull request merged**
