### PR TITLE
Add minProperties/maxProperties to attributes

### LINKED ISSUE #1373: [bug] Unknown named property "minProperties"
I use the schema:
```php
#[OA\Schema(schema: 'SchemaName', properties: [
    new OA\Property(property: 'property1', type: 'object', minProperties: 1, properties: [
        new OA\Property(property: 'property2', type: 'string'),
        new OA\Property(property: 'property3', type: 'string'),
    ]),
], additionalProperties: false)]
```
"minProperties" is ignored and says it's unknown.

The same, describing with the annotations works fine.

### PR DESCRIPTION
**Pull request by DerManoMann**
Fixes #1373

### CODE REVIEW

**Comment by jdecool** [comment]
This PR has been tagged as a bug fix (https://github.com/zircote/swagger-php/releases/tag/4.5.4).

But it potentially introduces a BC break in applications as the constructor definition as changed, and new fields are not optional, no ?

**Comment by DerManoMann** [comment]
Good point. I've never considered that, mostly because I've never used attributes without using named parameters.

The main reason for the order I inserted them was to keep them the same as they are defined in the annotations.

**Comment by jdecool** [comment]
>  I've never considered that, mostly because I've never used attributes without using named parameters.

Neither me.

But I've noticed that on one project I'm currently working on

**Comment by DerManoMann** [comment]
Apologies. I hope we'll do better next time.

I did add a note to the release notes, but for practical purposes that is mostly cosmetic I suppose.

**Pull request merged**
