### PR TITLE
Improve api doc

### PR DESCRIPTION
**Pull request by gnovaro**
- Add summary
- Add tags for group calls

### CODE REVIEW

**Comment by DerManoMann** [comment]
Changes look good except for the code style issues. Looking at the details its just switching to using single quotes instead of double quotes.

**Comment by gnovaro** [comment]
I try to find how to add the sercurity to attibutes for example this type

`security={{"bearerAuth": {} }},`

**Comment by DerManoMann** [comment]
Uh, not quite sure what the issue is here. Either php-cs-fixer defaults have changed or your branch is behind master.
Could you try to rebase your branch on master?

**Comment by DerManoMann** [comment]
> I try to find how to add the sercurity to attibutes for example this type
> 
> `security={{"bearerAuth": {} }},`

The misc example has some security related annotations which should be quite similar for attributes: https://github.com/zircote/swagger-php/blob/master/Examples/misc/OpenApiSpec.php

**Comment by DerManoMann** [comment]
I update master so a new rebase/merge should fix the remaining build issues.

**Comment by DerManoMann** [comment]
@gnovaro Looks like some mission!  When updating the example annotations/attributes the corresponding spec files (.yaml) need to be updated too to reflect those changes.

In particular you'll need to make the same changes here: https://github.com/gnovaro/swagger-php/blob/patch-1/Examples/using-links-php81/using-links-php81.yaml

**Comment by DerManoMann** [comment]
It really pays to run the tests locally before commiting :)

Run tests:
```shell
   composer test
```

Fix code style:
```shell
   composer cs
```

Finally, there is a cheat to update the example yaml files by uncommenting this line: https://github.com/zircote/swagger-php/blob/master/tests/ExamplesTest.php#L185
You will have to make sure to review the changes - in this case the changes should be pretty obvious and only affect a single (yaml) file.

**Comment by DerManoMann** [comment]
@gnovaro Just checking in - looks like you are almost there. I think one more round of code style fixes and updating the `.yaml` file should do the trick.

**Review by DerManoMann — CHANGES_REQUESTED** [review]
Looking good, just one more round of fixing code style issues :)

**Comment by DerManoMann** [comment]
Thanks @gnovaro

**Pull request merged**
