### PR TITLE
Add missing `ref` parameter for RequestBody.php

### PR DESCRIPTION
**Pull request by lempzz**
Additional fix for issue https://github.com/zircote/swagger-php/issues/1172

### CODE REVIEW

**Comment by DerManoMann** [comment]
🙂

**Comment by DerManoMann** [comment]
Thanks @lempzz

**Comment by lempzz** [comment]
@DerManoMann no problem 😊. How long to wait for new release?

**Comment by DerManoMann** [comment]
Not long 😁

**Pull request merged**
