### PR TITLE
add deserializer and test

### PR DESCRIPTION
**Pull request by csimplestring**
In this PR: 

- Support deserialize a json string to specific Swagger Annotations object;
- Add tests;

### CODE REVIEW

**Comment by bravo-kernel** [comment]
nice job mr. @csimplestring

**Comment by bravo-kernel** [comment]
@csimplestring could you add a simple usage example to the readme (so new users know the feature exists) before I merge this?

**Comment by csimplestring** [comment]
@bravo-kernel  Done. I added a short example in readme. Please check.

**Comment by bravo-kernel** [comment]
thanks, could you please rebase against current master to solve the merge conflict?

**Comment by bravo-kernel** [comment]
Good job mr. @csimplestring. Not sure if you are familiar with phpcs but the Travis build fails due to errors related to PSR-2 coding standards.

Please take a look at the error descriptions found [here](https://travis-ci.org/zircote/swagger-php/jobs/109003678) and let me know if you need assistance solving them.

**Comment by csimplestring** [comment]
@bravo-kernel  Thanks for reminding. I am working on it.

**Comment by bravo-kernel** [comment]
Much obliged mr. @csimplestring :clap: You will be mentioned in the next release.

**Comment by csimplestring** [comment]
@bravo-kernel Thanks, My pleasure. :smiley:

**Comment by bravo-kernel** [comment]
@csimplestring https://github.com/zircote/swagger-php/releases/tag/2.0.6

**Pull request merged**
