### PR TITLE
Annotations\Parameters - declare consts for IN_

### PR DESCRIPTION
**Pull request by ovr**
Hey!

I started to working on https://github.com/ovr/swagger-assert-helper
I prefer to use constants instead of string

Can we declare it?

Thanks

### CODE REVIEW

**Comment by bfanger** [comment]
Sorry, but when the constants are just as readable as the strings they contain I prefer the shorter string notation.

swagge-assert-helper looks useful, let know when you think it's ready so I can add a link to it from de swagger-php docs

**Comment by ovr** [comment]
> Sorry, but when the constants are just as readable as the strings they contain I prefer the shorter string notation.

Didnt understand you, I dont known how to name this constants in shorter way.

> swagge-assert-helper looks useful, let know when you think it's ready so I can add a link to it from de swagger-php docs

will ping you, after first release :)

Thanks

**Comment by bfanger** [comment]
Examples: 

```php
if (json_last_error() === 4) // ❌ short but not readable, the intent is unclear 
if (json_last_error() === JSON_ERROR_SYNTAX) // ✅ more code, but clarifies intent/meaning.
if ($parameter->in === Parameter::IN_BODY) // ✅ intent clear, but verbose. little bonus: IDE completion.
if ($parameter->in === 'body') // ✅ intent clear, less code, little bonus: shows the type (a string)
```

I find the `if ($parameter->in === 'body')` notation the most elegant solution, that's why I didn't merge your pull request.

**Comment by ovr** [comment]
okey, thank you for this explanation of your opinion 👍

**Pull request closed without merging**
