### PR TITLE
PHP 7.4 Support

### PR DESCRIPTION
**Pull request by sunspikes**
Adds PHP 7.4 Support

### CODE REVIEW

**Comment by martinatseequent** [comment]
:+1:

**Comment by vkhramtsov** [comment]
Any news here?

**Comment by bfanger** [comment]
I'll (probably) merge this when PHP 7.4 is released and available via homebrew.

**Comment by wedi** [comment]
I'd say that trying to index a variable that is no array is an error today already or code smell at least and does not depend on PHP 7.4 but eight days patience I have. 👍

**Comment by TilmannBach** [comment]
i can confirm that these changes makes swagger-php compatible to my PHP 7.4 installation!

**Comment by douglasjam** [comment]
let's merge it, it's live!  🎉

**Comment by bfanger** [comment]
Merged and released as 3.0.3

**Pull request merged**
