### PR TITLE
Add var type detection when null is also set 

### PR DESCRIPTION
**Pull request by thePanz**
Backport of 6867461

### CODE REVIEW

**Comment by Tobion** [comment]
@bfanger could you merge this please and potentially release a new 2.x version?

**Comment by Tobion** [comment]
What I've found is that `@var string|null` and `@var MyClass|null` works now as the tests also prove. But `@var MyClass[]|null` does not work while `@var MyClass[]` itself works. So there seems to be a missing case for the `|null` handling.

**Comment by thePanz** [comment]
Thanks @bfanger . Could you tag a new release on the 2.x branch?

**Comment by thePanz** [comment]
@bfanger can you tag a new release with the changes from this PR? thank you :)

**Pull request merged**
