### PR TITLE
Documenting Attribute references

### PR DESCRIPTION
**Pull request by MalekMneri**
I improved the documentation for the Post Attribute. if it is accepted, I'll try to continue with other attributes.

### CODE REVIEW

**Comment by MalekMneri** [comment]
Happy to be of help!
I tried updating the files in src/Attributes like this: 
image
but it won't generate after running `composer docs:gen`
Do I need to update the file tools/src/Docs/RefGenerator.php or is there another way to add a description to attributes.

**Comment by DerManoMann** [comment]
The refregenerator does currently not use those docblock comments. I wasn't sure yet if it is better to focus on improving the already existing docblocks in the annotation classes and re-use those for the corresponding vars in the attribute classes.
That way we only do it once and avoid duplication. If you are happy to go down that path I'll try to find some time to update the script - something on my list already anyway...

**Comment by MalekMneri** [comment]
yeah I think updating the existing annotations docblocks would be more efficient. 
I'd love to work on them after you update the script so feel free to tag me in the PR.

**Comment by DerManoMann** [comment]
Try PR #1439

**Comment by DerManoMann** [comment]
@MalekMneri If you think this works well enough let me know so I can merge. After that you can create a new PR with your changes and test locally.

**Comment by MalekMneri** [comment]
Looks good! 
I was able to update the documentation using `composer docs:gen`
Feel free to merge it so I can continue :)

**Comment by DerManoMann** [comment]
All merged - hope the syntax for refs/@see and other markup make sense :)

**Pull request closed without merging**
