### PR TITLE
adding scrutinizer

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by bfanger** [comment]
What is scrutinizer and how does the swagger-php project benefit from this change?

**Comment by bravo-kernel** [comment]
It's a code inspection platform and will usually detect (most likely) desirable code changes like unused classes, strange indenting, etc. It has been said that scrutinizer is not the most friendly/trusty though. A very good, fast and user friendly open source alternative could be https://styleci.io. Has a lot of easy [filters](https://styleci.readme.io/docs/fixers).

For some sample reports and detections you might like to take a look at some of the [improvements styleci found for my cakephp-swagger repo](https://styleci.io/repos/45741948), `Show Details` buttons.

**Comment by spekulatius** [comment]
Hello @bravo-kernel 

do you have more information on what you mentioned about Scrutinizer? I haven't heard that before.

Spek

**Comment by bravo-kernel** [comment]
To be honest mr @spekulatius :

- I do not have any data to support my claim
- did hear people complain in irc about issues
- admit that any preference is probably subjective anyway

More important... I was not trying to disqualify scrutinizer but more trying to point out to mr. @bfanger that there are alternative CIs out there and thus, choices to be made.

**Comment by bfanger** [comment]
Travis-CI now checks for stylistic (PSR2) preferences. additional scrutinization is not needed.

**Pull request closed without merging**
