### PR TITLE
Misc annotation improvements

### PR DESCRIPTION
**Pull request by pegro**
- Allow JsonContent in RequestBody annotations
- Allow AdditionalProperties to be nested in Property annotations to allow free-form objects
- JsonContent: allow single example (see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-10)

### CODE REVIEW

**Comment by pegro** [comment]
Any comments on these?

**Comment by pegro** [comment]
@bfanger any reasons, why?

**Comment by bfanger** [comment]
Hmm, strange. I did (temporary) remove the 3.x branch from GitHub (as it's now merged into master), could that cause issue to be closed?

**Comment by bfanger** [comment]
Thanks! merged as 20f3d07

**Pull request closed without merging**
