### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by iGusev**

### CODE REVIEW

**Comment by ovr** [comment]
ping @zircote

**Comment by felipemarques** [comment]
ping @zircote

**Comment by bravo-kernel** [comment]
Looks good to me Mr. @bfanger

**Comment by bravo-kernel** [comment]
@iGusev Could you add a blank line above your `/**` to keep things consistent with the other examples? Thank you kindly.

**Comment by iGusev** [comment]
@bravo-kernel done

**Comment by bravo-kernel** [comment]
Please rebase and squash so we keep our commit history clean.

Not sure if you're famliar with the process but something like this should do:
```bash
git rebase -i HEAD~2
```
then change the second commit from `pick` to `squash`, save and the `push origin yourbranch --force`

**Comment by bravo-kernel** [comment]
ping @iGusev

**Pull request merged**
