### PR TITLE
Improve parser part 2

### PR DESCRIPTION
**Pull request by DerManoMann**
Here is the second part of the trait fixes. In fact, it s a lot more....
* Normalized handling of namespaces across classes/interfaces/traits
* Fix defunct MergeInterfaces processor
* Add support for multiple implements
* Add new `InheritInterfaces` processor and use as default instead of `MergeInterfaces`
* Add new `InheritTraits` processor and use as default instead of `MergeTraits`

This PR is loosely based on PR #779 but will need some work once that is merged. The idea is to keep the PRs small to improve the chance of a review :) In that respect this PR can wait until #779 is done. However, this is a good place to start testng for anyone interested in using traits or interfaces...

### CODE REVIEW

**Comment by bfanger** [comment]
Oh, no,  I've merged in the wrong order (again). Splitting the PR up creates more maintainer workin merge conflicts 😅

**Comment by bfanger** [comment]
I've tried to merge the changes https://github.com/zircote/swagger-php/tree/failed-merge-attempt.
But missed something (tests are failing), could you fix the merge confict?

**Comment by DerManoMann** [comment]
sure, i didn't expect you to merge that yet. as mentioned this will need a little more work once the other PR is merged

**Comment by DerManoMann** [comment]
Sorry for the mess - I should have flagged this one as WIP.

Rebased and fixed. Not sure how closely you've looked at the changes, but I feel this is a lot cleaner (and working!) than what was there before.

Not sure if switching to the inherit processors for interfaces/traits is controversial or not, but in the end it shouldn't matter for the final outcome. Still, maybe this requires a minor version bump to 3.1.0...?

**Comment by bfanger** [comment]
I haven't been following semver for this library. I've matched the version to the spec. And used the patch number for all changes.

I haven't looked in detail at how this pr works, but liked all the examples/tests it adds.

Do you want to give this pr more thought, or is can i merge this one?

**Comment by DerManoMann** [comment]
I think it is good to go - it is BC and mostly fixes things that were broken in some shape or form.
If people have the urge to use the merging processors they still can do that...

**Pull request merged**
