### PR TITLE
Improve oas3 conformity

### PR DESCRIPTION
**Pull request by DerManoMann**
Improve conforming to the [OAS3 specs](http://spec.openapis.org/oas/v3.0.3).

Using https://github.com/stoplightio/spectral to fix issues with test annotations and code:
```
for ff in `find Examples -name *.yaml`; do spectral lint $ff; done
```

### CODE REVIEW

**Comment by Doqnach** [comment]
> Improve conforming to the [OAS3 specs](http://spec.openapis.org/oas/v3.0.3).
> 
> Using https://github.com/stoplightio/spectral to fix issues with test annotations and code:
> 
> 
> ```
> for ff in `find Examples -name *.yaml`; do spectral lint $ff; done
> ```

how far nested are the examples? is it possible to use `ls` instead? because it's a whole lot faster than `find` if the depth is fixed.

**Comment by DerManoMann** [comment]
Yes, ls would work too I guess. There is some nesting but since we are talking about around a 100 files in total it won't make much of a difference.

**Comment by Doqnach** [comment]
> Yes, ls would work too I guess. There is some nesting but since we are talking about around a 100 files in total it won't make much of a difference.

Do you mean `ls` won't that much of a difference? Most of the time I'm running the code in a docker container on MacOS for development. Unfortunately there is a huge disk IO issue in that setup, making `find` severely slower than `ls`. On the host machine it might not make that much of a difference, but within the container it does greatly. I understand that this is maybe a use-case that isn't for everyone, but faster=better :-P.

**Comment by DerManoMann** [comment]
Oh well, so for the record this results in the same list of files:
```
ls Examples/*/*.yaml Examples/*/*/*.yaml
```

**Comment by DerManoMann** [comment]
In case anyone is interested, here is the current status...
```
OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-traits/using-traits-inherit.yaml
   1:1   warning  oas3-api-servers                    OpenAPI `servers` must be present and non-empty array.
   1:1   warning  openapi-tags                        OpenAPI object should have non-empty `tags` array.
   2:6   warning  info-contact                        Info object should contain `contact` object.
   2:6   warning  info-description                    OpenAPI object info `description` must be present and non-empty string.
  7:12   warning  operation-description               Operation `description` must be present and non-empty string.
  7:12     error  path-params                         The operation does not define the parameter `{id}` expected by path `/entities/{id}`.
  9:11   warning  operation-tag-defined               Operation tags should be defined in global tags.
  10:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
  19:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
  23:9   warning  operation-description               Operation `description` must be present and non-empty string.
  23:9     error  path-params                         The operation does not define the parameter `{product_id}` expected by path `/products/{product_id}`.
  25:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
  26:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
  35:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
  68:14  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
  75:18  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
  77:13  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 106:19  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.

✖ 18 problems (2 errors, 16 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-traits/using-traits-merge.yaml
  1:1   warning  oas3-api-servers                    OpenAPI `servers` must be present and non-empty array.
  1:1   warning  openapi-tags                        OpenAPI object should have non-empty `tags` array.
  2:6   warning  info-contact                        Info object should contain `contact` object.
  2:6   warning  info-description                    OpenAPI object info `description` must be present and non-empty string.
  7:12  warning  operation-description               Operation `description` must be present and non-empty string.
  7:12    error  path-params                         The operation does not define the parameter `{id}` expected by path `/entities/{id}`.
  9:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
 10:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 19:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
  23:9  warning  operation-description               Operation `description` must be present and non-empty string.
  23:9    error  path-params                         The operation does not define the parameter `{product_id}` expected by path `/products/{product_id}`.
 25:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
 26:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 35:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
 40:22  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 42:11  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 44:12  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 46:11  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 48:14  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 50:18  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 52:13  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 85:19  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.

✖ 22 problems (2 errors, 20 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/petstore-3.0/petstore-3.0.yaml
  18:9   warning  operation-description   Operation `description` must be present and non-empty string.
  25:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
  37:10  warning  operation-description   Operation `description` must be present and non-empty string.
  44:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
 169:10  warning  operation-description   Operation `description` must be present and non-empty string.
 196:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
 204:12  warning  operation-description   Operation `description` must be present and non-empty string.
 224:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
 235:10  warning  operation-description   Operation `description` must be present and non-empty string.
 289:10  warning  operation-description   Operation `description` must be present and non-empty string.
 358:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
 377:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
 381:10  warning  operation-description   Operation `description` must be present and non-empty string.
 388:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
  392:9  warning  operation-description   Operation `description` must be present and non-empty string.
  435:9  warning  operation-description   Operation `description` must be present and non-empty string.
 440:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
  444:9  warning  operation-description   Operation `description` must be present and non-empty string.
  444:9  warning  operation-tags          Operation should have non-empty `tags` array.
  468:9  warning  operation-tags          Operation should have non-empty `tags` array.
 487:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.
 492:12  warning  operation-tags          Operation should have non-empty `tags` array.
 504:17  warning  operation-2xx-response  Operation must have at least one `2xx` response.

✖ 23 problems (0 errors, 23 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/example-object/example-object.yaml
  1:1  warning  oas3-api-servers       OpenAPI `servers` must be present and non-empty array.
  1:1  warning  openapi-tags           OpenAPI object should have non-empty `tags` array.
  2:6  warning  info-contact           Info object should contain `contact` object.
  2:6  warning  info-description       OpenAPI object info `description` must be present and non-empty string.
 7:10  warning  operation-description  Operation `description` must be present and non-empty string.
 7:10  warning  operation-operationId  Operation should have an `operationId`.
 7:10  warning  operation-tags         Operation should have non-empty `tags` array.

✖ 7 problems (0 errors, 7 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/misc/misc.yaml
  1:1  warning  openapi-tags           OpenAPI object should have non-empty `tags` array.
  2:6  warning  info-contact           Info object should contain `contact` object.
  2:6  warning  info-description       OpenAPI object info `description` must be present and non-empty string.
 17:9  warning  operation-description  Operation `description` must be present and non-empty string.
 17:9  warning  operation-operationId  Operation should have an `operationId`.
 17:9  warning  operation-tags         Operation should have non-empty `tags` array.

✖ 6 problems (0 errors, 6 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-interfaces/using-interfaces-inherit.yaml
  1:1   warning  oas3-api-servers                    OpenAPI `servers` must be present and non-empty array.
  1:1   warning  openapi-tags                        OpenAPI object should have non-empty `tags` array.
  2:6   warning  info-contact                        Info object should contain `contact` object.
  2:6   warning  info-description                    OpenAPI object info `description` must be present and non-empty string.
  7:9   warning  operation-description               Operation `description` must be present and non-empty string.
  7:9     error  path-params                         The operation does not define the parameter `{id}` expected by path `/products/{id}`.
  9:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
 10:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 19:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.

✖ 9 problems (1 error, 8 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-interfaces/using-interfaces-merge.yaml
  1:1   warning  oas3-api-servers                    OpenAPI `servers` must be present and non-empty array.
  1:1   warning  openapi-tags                        OpenAPI object should have non-empty `tags` array.
  2:6   warning  info-contact                        Info object should contain `contact` object.
  2:6   warning  info-description                    OpenAPI object info `description` must be present and non-empty string.
  7:9   warning  operation-description               Operation `description` must be present and non-empty string.
  7:9     error  path-params                         The operation does not define the parameter `{id}` expected by path `/products/{id}`.
  9:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
 10:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 19:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
 40:22  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.

✖ 10 problems (1 error, 9 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/openapi-spec/openapi-spec.yaml
   1:1   warning  oas3-api-servers       OpenAPI `servers` must be present and non-empty array.
   1:1   warning  openapi-tags           OpenAPI object should have non-empty `tags` array.
   2:6   warning  info-contact           Info object should contain `contact` object.
   2:6   warning  info-description       OpenAPI object info `description` must be present and non-empty string.
   7:9   warning  operation-description  Operation `description` must be present and non-empty string.
   7:9   warning  operation-tags         Operation should have non-empty `tags` array.
  29:9   warning  operation-description  Operation `description` must be present and non-empty string.
  29:9   warning  operation-tags         Operation should have non-empty `tags` array.
  55:9   warning  operation-description  Operation `description` must be present and non-empty string.
  55:9   warning  operation-tags         Operation should have non-empty `tags` array.
  89:9   warning  operation-description  Operation `description` must be present and non-empty string.
  89:9   warning  operation-tags         Operation should have non-empty `tags` array.
 121:10  warning  operation-description  Operation `description` must be present and non-empty string.
 121:10  warning  operation-tags         Operation should have non-empty `tags` array.
  146:9  warning  operation-description  Operation `description` must be present and non-empty string.
  146:9  warning  operation-tags         Operation should have non-empty `tags` array.

✖ 16 problems (0 errors, 16 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-refs/using-refs.yaml
  1:1   warning  oas3-api-servers                    OpenAPI `servers` must be present and non-empty array.
  1:1   warning  openapi-tags                        OpenAPI object should have non-empty `tags` array.
  2:6   warning  info-contact                        Info object should contain `contact` object.
  2:6   warning  info-description                    OpenAPI object info `description` must be present and non-empty string.
  7:9   warning  operation-description               Operation `description` must be present and non-empty string.
  9:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
 10:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 11:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
 14:11  warning  operation-description               Operation `description` must be present and non-empty string.
 16:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
 17:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 21:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
 28:10  warning  operation-description               Operation `description` must be present and non-empty string.
 30:11  warning  operation-tag-defined               Operation tags should be defined in global tags.
 31:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 35:17  warning  operation-2xx-response              Operation must have at least one `2xx` response.
 78:21    error  oas3-schema                         `product_in_body` property should have required property `name`.

✖ 17 problems (1 error, 16 warnings, 0 infos, 0 hints)

```

**Comment by DerManoMann** [comment]
Down to one error which might be a validator bug...
I left out some things in the interface/traits examples as those also act as `tests`...

```
OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-traits/using-traits-inherit.yaml
  18:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
  35:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
  89:18  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
  91:13  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 120:19  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.

✖ 5 problems (0 errors, 5 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-traits/using-traits-merge.yaml
 18:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 35:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 49:22  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 51:11  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 53:12  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 55:11  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 57:14  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 59:18  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 61:13  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.
 94:19  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.

✖ 10 problems (0 errors, 10 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-interfaces/using-interfaces-inherit.yaml
 18:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.

✖ 1 problem (0 errors, 1 warning, 0 infos, 0 hints)

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-interfaces/using-interfaces-merge.yaml
 18:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 48:22  warning  oas3-unused-components-schema       Potentially unused components schema has been detected.

✖ 2 problems (0 errors, 2 warnings, 0 infos, 0 hints)

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

OpenAPI 3.x detected

/home/martinr/projects/swagger-php/Examples/using-refs/using-refs.yaml
 18:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 41:20  warning  operation-operationId-valid-in-url  operationId may only use characters that are valid when used in a URL.
 88:21    error  oas3-schema                         `product_in_body` property should have required property `name`.

✖ 3 problems (1 error, 2 warnings, 0 infos, 0 hints)


```

**Comment by DerManoMann** [comment]
Closing this in favour of a much smaller PR that only addresses the actual code change

**Pull request closed without merging**
