### PR TITLE
Update Getting-started.md

### PR DESCRIPTION
**Pull request by baskan**

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Nice catch, thanks!

**Comment by bravo-kernel** [comment]
@bfanger totally missed the targeted branch here, updates should target `master` branch right? Sorry about this, lack of :coffee:

**Comment by bfanger** [comment]
Removed all branches except master & gh-pages to avoid confusion. making it a easy target for pull requests and light development, we can create branches for big features as needed.

**Comment by bravo-kernel** [comment]
Thank you kindly mr. @bfanger :relaxed:

**Pull request merged**
