### PR TITLE
Added the option: "operationid".

### PR DESCRIPTION
**Pull request by byjg**
I am developing a Route Generator for REST calls based on the swagger.json. 

As I am using your library to create my JSON file and you have the context where the Annotation was placed I made a small change to override the "operationid" with the Namespace, class and method of the annotation context. 

This change does not break compatibility because it is optional.

### CODE REVIEW

**Comment by bfanger** [comment]
Nice, feature! Could you reimplement it as a processor?

I'd like to keep Analysis.php simple, the command line option would then enable the optional processor using: `Analysis::registerProcessor(new DetectOperationId())` 
or something along those lines.

**Comment by byjg** [comment]
Thank you!

I did it using Processor.

**Comment by byjg** [comment]
Hello, is there any comments about this PR?

**Comment by bfanger** [comment]
Nope, just have to find some free time to merge it into master and the 3.x branch.
I’ll probably enable it by default on the 3.x branch.

**Comment by byjg** [comment]
Good to know! As you want to merge it in the branch 3.x I created the PR #487 specific for the branch 3.x;

**Comment by bfanger** [comment]
Merged as 941f0b62b7a2f2d784d5de13b146682e65449f53  

I've added some features:

- Ability to set the operationId manually in the annotation
- Ability to hide a specific operationId: `@SWG\GET(operationId=null)`.
- Also generate an operationId when not in a class and/or namespace context.
- Removed --operationid in favor of a generic --processor argument.

**Pull request closed without merging**
